version: '3.8'

services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  server:
    build:
      context: ./Server
    environment:
      DATABASE_URL: postgres://postgres:123456@db:5432/postgres
    ports:
      - "5000:5000"
    depends_on:
      - db

  client:
    build:
      context: ./Client
    ports:
      - "5173:5173"  # Map Vite dev server port
    depends_on:
      - server

volumes:
  pgdata: